//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWCF.ReferenceNegocios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceNegocios.IServiceNegocios")]
    public interface IServiceNegocios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNegocios/Clientes", ReplyAction="http://tempuri.org/IServiceNegocios/ClientesResponse")]
        ServicioWCF.ReferenceNegocios.Cliente[] Clientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNegocios/Clientes", ReplyAction="http://tempuri.org/IServiceNegocios/ClientesResponse")]
        System.Threading.Tasks.Task<ServicioWCF.ReferenceNegocios.Cliente[]> ClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNegocios/ClienteXNombre", ReplyAction="http://tempuri.org/IServiceNegocios/ClienteXNombreResponse")]
        ServicioWCF.ReferenceNegocios.Cliente[] ClienteXNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNegocios/ClienteXNombre", ReplyAction="http://tempuri.org/IServiceNegocios/ClienteXNombreResponse")]
        System.Threading.Tasks.Task<ServicioWCF.ReferenceNegocios.Cliente[]> ClienteXNombreAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNegociosChannel : ServicioWCF.ReferenceNegocios.IServiceNegocios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNegociosClient : System.ServiceModel.ClientBase<ServicioWCF.ReferenceNegocios.IServiceNegocios>, ServicioWCF.ReferenceNegocios.IServiceNegocios {
        
        public ServiceNegociosClient() {
        }
        
        public ServiceNegociosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNegociosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNegociosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNegociosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicioWCF.ReferenceNegocios.Cliente[] Clientes() {
            return base.Channel.Clientes();
        }
        
        public System.Threading.Tasks.Task<ServicioWCF.ReferenceNegocios.Cliente[]> ClientesAsync() {
            return base.Channel.ClientesAsync();
        }
        
        public ServicioWCF.ReferenceNegocios.Cliente[] ClienteXNombre(string nombre) {
            return base.Channel.ClienteXNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<ServicioWCF.ReferenceNegocios.Cliente[]> ClienteXNombreAsync(string nombre) {
            return base.Channel.ClienteXNombreAsync(nombre);
        }
    }
}
